version: "3.8"
services:
  api:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    ports:
      - "8080:8080"
    command: [ "./api" ]

  test:
    build:
      dockerfile: .docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt
